### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by humphd** [tarasglek/chatcraft.org#263] opened 2023-10-01 14:12 UTC
I notice that when clicking on a previous chat, the "scroll to" logic is causing the entire page to scroll up:

<img width="913" alt="Screenshot 2023-10-01 at 10 10 11 AM" src="https://github.com/tarasglek/chatcraft.org/assets/427398/98aa9925-84e8-44b7-a935-4bb0677615d8">

The amount looks to be about the same amount as the prompt form, so it's likely connected to the redesign we just landed.

**Comment by Amnish04** [comment] 2023-10-23 18:14
@humphd 
I tried to reproduce this bug.
When I click on this button
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/457a253b-a2fd-4502-8af0-178f51374b08)

It brings the chat to the top of the page like so
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/8815c333-afff-4f54-8eb5-5848c88daf24)

But shouldn't that be the expected behavior. If not, what is the expected scroll behavior.

**Comment by humphd** [comment] 2023-10-23 18:16
That's expected, yes.

The bug I'm talking about happens if you open the sidebar (hit the hamburger menu, top-left) and then go to old chats in "Saved Chats" and click on those.  As you do, it will jump the whole viewport.

I suspect this is somehow due to the height of the page being different, and it can't scroll up enough, so it ends up moving the entire container.  It's likely somehow related to scroll restoration in React Router DOM, but I haven't dug deeply.

**Comment by Amnish04** [comment] 2023-10-23 18:21
Oh I see what you mean now. Will take a look.

**Comment by Amnish04** [comment] 2023-10-24 02:21
I noticed that the `main` element that is the root of the entire DOM, has a lot of extra height due to some reason that is hidden in what I believe as a hacky way by setting overflow to hidden. All that extra height becomes visible after removing that style. I guess that is the space pushed up on every redirect. If we can somehow eliminate this space, maybe the issue gets fixed, but not sure.

![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/27541c1b-d0ed-43b2-8a61-b5e9d210d58c)

**Comment by Amnish04** [comment] 2023-10-24 02:53
Yes, I am close. Whenever we click these links on the sidebar, the newly rendered page is scrolled such that the link is at the top.

**Example1:**
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/d495818e-0f65-4edb-9353-261a637beec7)

**Example2:** 
![image](https://github.com/tarasglek/chatcraft.org/assets/78865303/087aee1e-8c4f-42f9-8c08-5bdc85d80ce2)


If we can scroll to top on each such render, it should be fixed.

**Closed** 2023-10-28 00:29 UTC
