### ISSUE TITLE
Cant login on Chrome

### ISSUE THREAD

**Issue by harrytormey** [tarasglek/chatcraft.org#101] opened 2023-06-09 03:04 UTC
1) Tapped icon to share.
2) Clicked github signin.
3) Went through github auth, landed back on chatcraft not logged in despite saying yes.
4) Not tapping sign in does not allow me to sign in or do anything so I cant share urls.

**Comment by harrytormey** [comment] 2023-06-09 03:10
Recording:
https://github.com/tarasglek/chatcraft.org/assets/79118283/d55d8abb-f06e-4fde-9c3f-4ff24763a961

**Comment by tarasglek** [comment] 2023-06-09 11:17
heard through backchannel that it's unclear why we require signin for sharing..should add a blurb saying that this is a spam-prevention measure

**Comment by humphd** [comment] 2023-06-23 01:02
I'm going to close this, since I can't reproduce.  Please re-open or file again if it becomes a blocker to anyone.

**Closed by humphd** 2023-06-23 01:02 UTC

**Comment by humphd** [comment] 2023-07-25 22:08
@harrytormey we figured out your issue, and I have a fix up for it in https://github.com/tarasglek/chatcraft.org/pull/179.  Sorry we couldn't figure this out sooner!
